name: Keep Render App Awake

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Render app
        run: |
          curl -sSf https://automl-nlzh.onrender.com || echo "App is sleeping or failed to respond"
